import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import "./globals.css";



export const inter = Inter({ subsets: ['latin'] })
export const raleway = Raleway({
  subsets: ['latin'], // Or other subsets as needed
  weight: ['400', '700'], // Specify desired weights
  variable: '--font-raleway', // Optional: for use with CSS variables in Tailwind
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body className={`${inter.className} ${raleway.variable}`}>
          <Header />
          <main className="min-h-screen">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
